server:
  port: 8081

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  # (선택) 개발 시 캐시 비활성화

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8081/login/oauth2/code/google
            scope:
              - profile
              - email

logging:
  level:
    org.springframework.security: DEBUG

